### ISSUE TITLE
FIRST PLAYTEST NEEDS

### ISSUE THREAD

**Issue by AjexRose** [Arcadia-Industries/Mystic-Station#2]
Other
- [x] Create special folders for Mystic Station content to avoid upstream merge hell (Partially done in #1 )

Renames || Solved in #6
- [x] Science to Arcaneology (magic version of science)
   - [x] Research Director to Master Arcanist
   - [x] Scientist to Mystic Researcher
   - [x] Research Assistant to Mystic Fledgling
   - [x] Rename salvage to otherspace explorer
- [x] Cargo to Logistics (cargo + science without the research)
   - [x] Cargo tech to Logistics Specialist
- [x] Command Renames
   - [x] Captain to Director
   - [x] Head of Security to Chief Security Officer
   - [x] Head of Personnel to Service Leader

these still need work
- [ ] Rename wizden job/stuff to the appropriate stuff (and remember to comment it)
  - [ ] Have announcements come from Nexus Command instead of Central Command
  - [ ] Replace all instances of NT to Arcadia Industries where appropriate
  - [ ] new captain gear relabeled as director
  - [ ] new HOS gear relabeled as Chief Security Officer
  - [ ] new HOP gear relabeled as Service Leader

Content
- [ ] Either a new map or a modified old map to fit the new game play
- [ ] Gateways being mapped for Otherspace Explorers
- [x] ~~Cull passengers~~ 
dont need todo this, just dont map passengers :godo:
- [x] ~~Move salvage content to Arcaneology~~
mapping, not dev
- [ ] Change planet generation
   - [ ] More dungeons
     - [ ] A few magic-ish dungeons
     - [ ] A few outpost dungeons
     - [ ] MAYBE port from frontier
   - [ ] Reduce the amount of rocks on the planets
   - [ ] Add hostile + passive mobs
   - [ ] Let element crystals be randomly generated on planets
- [x] Adding the element crystals (Each one will need a in world minable sprite and a item sprite) (#1)
   - [x] Pyro (fire)
   - [x] Geo (earth/rock)
   - [x] Electro (electric)
   - [x] Dendro (plants)
   - [x] Hydro (water)
   - [x] Anemo (wind)
   - [x] Cryo (ice)
   - [x] Chrono (time)
   - [x] Spaco (space)
   - [x] Helio (light)
   - [x] Tenebro (dark)
   - [x] Pondo (gravity
- [x] Get Crystals to be stackable #5 
- [ ] Get Crystals to be inserted into lathes
- [ ] Machine Building 
   - [ ] Re-add Part Upgrades from Frontier
   - [ ] Sprites and Yamls for unique parts for machines
~~Motherboard circuits (This is like a machine level. Level 1 would get you a regular lathe, Level 2 would get you a hyper lathe, etc)~~ 
~~Firmware (These are the replacements for circuits. Dependent on motherboard)~~
makes construction more complex then needed, so removed
 - [ ] Mechanism Fabricator (Round start machine that builds machine parts)
 - [ ] Purchasable Data Packs for more advanced non-technomancy things
 (data packs are just research disks that can be purchased for non-magical items)
 - [ ] At least 6 different construction/lathe recipes for each elemental crystal
 - [X] ~~Add Mail Carriers from Frontier/DeltaV~~
 - Supplimented by WizDen mail system. 
 - Could probably still port more QoL stuff/more mail content
- [x] PDAs for new + renamed roles #10 
- [ ] New clothing for new roles
- [ ] Rename clothing + job spawners for replaced roles
  - [ ] Scientist, Research Assistant, and Research Director gear relabeled as Mystic Researcher, Fledgling, and Master Arcanist
  - [ ] The Arcanauts
 - [x] New accesses for Arcaneology #10 
 - [x] Job HUD Icons for Arcaneology #10 
 - [ ] Logistics Gameplay
   - Factorio-eqsue machines
   - [ ] at least 5 different low-value constructables
   - [ ]  at least 3 different mid-value constructables
   - [ ] at least 2 different high-value constructables
   - [ ] a different machine for fabricating each different kind of constructable.
